"use client";
import BestProducts from "@/components/home/best-products";
import DailyDeals from "@/components/home/daily-deals";
import HeroSection from "@/components/home/hero-section";
import JustLanding from "@/components/home/just-landing";
import Recommended from "@/components/home/recommended";
import CTASection from "@/components/home/cta-section";
import WonOffer from "@/components/home/won-offer";
import SliderSection from "@/components/home/slider-section";
import DropShip from "@/components/home/drop-ship";
import Head from "next/head";
// import DropShip from "@/components/home/drop-ship";

export default function Home({ bestProducts }) {
  return (
    <>
      <Head>
        <title>Home - Wonport</title>
        <meta name="description" content="Generated by create next app" />
      </Head>
      <HeroSection />
      <DropShip />
      <BestProducts bestProducts={bestProducts} />
      <DailyDeals />
      <Recommended recommendedProducts={bestProducts} />
      <SliderSection />
      <WonOffer />
      <JustLanding JustLandingProducts={bestProducts} />
      <CTASection />
    </>
  );
}

export async function getStaticProps() {
  const res = await fetch(
    `${process.env.NEXT_PUBLIC_BACKEND_URL}/product/getAll?limit=5`
  );
  const data = await res.json();
  const bestProducts = data?.data?.products || [];

  return {
    props: { bestProducts },
    revalidate: 300,
  };
}
